### PR TITLE
Failed assertion doesn't report it

### PR DESCRIPTION
**Pull request by maiis**

### CODE REVIEW

**Comment by smockle** [comment]
Hi @maiis, thanks for the PR! Could you please provide some context for this change?

**Comment by maiis** [comment]
Hello,

on my teamcity I had "2 tests failed", but still showing the green tick ✅ "build success".

This change will make it fail. Does that make sense ?

**Comment by smockle** [comment]
@maiis Yes, thank you for clarifying. Thanks again for the contribution! This is shipped in version 1.2.0.

**Comment by maiis** [comment]
@smockle awesome thanks, my build is now failing ❌ 👍 First time I'd say that 😉

**Pull request merged**
